apiVersion: v1
kind: Service
metadata:
  name: mortgage-loan-catalogs
spec:
  selector:
    app: mortgage-loan-catalogs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP


